### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by lstoryc** [soraping/re-tsc#2]
node: 10.13.0

tsconfig.json
---
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "outDir": "dist",
    "declaration": true,
    "declarationMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "tests/**/*.vue"
  ],
  "exclude": [
    "node_modules",
    "dist",
    "tests/**/*.ts",
    "tests/**/*.tsx",
    "tests/**/*.vue"
  ]
}
****
---

错误信息
----
(node:14892) UnhandledPromiseRejectionWarning: SyntaxError: D:\devSpaces\others\ts-demo3-ui\tsconfig.json: Unexpected token } in JSON at position 905     at JSON.parse (<anonymous>)     at D:\devSpaces\others\ts-demo3-ui\node_modules\jsonfile\index.js:33:18     at D:\devSpaces\others\ts-demo3-ui\node_modules\graceful-fs\graceful-fs.js:90:16     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3) (node:14892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) (node:14892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----

请问这是啥原因

**Comment by soraping** [comment]
其实用 webpack 的alias 就可以完全解决所需要的了，这个库只为了nodejs没有alias的情况，做字符替换的操作

**Comment by lstoryc** [comment]
知道，现在我在弄一个基于ts的UI库，使用 tsc 生成d.ts 这时候webpack并没有介入，所以找到你这个插件，，可是发现有点问题，不知道有没什么解决办法？

**Comment by soraping** [comment]
具体描述下你所要实现的项目功能，引入了哪些模块，我好本地复现调试

**Comment by lstoryc** [comment]
https://github.com/Lstoryc/ts-demo3-ui.git  

clone这个项目，

然后执行 
npm run build:dts

会提示下面错误信息
---
PS F:\ts-demo3-ui> npm run build:dts

> ts-demo3-ui@0.1.4 build:dts F:\ts-demo3-ui
> rimraf types dist lib && npx ts-paths build ./ -t tsconfig.json -d -l 2

[ts-paths] - 2019-5-17 17:07:45   编译文件夹绝对路径 => F:\ts-demo3-ui
[ts-paths] - 2019-5-17 17:07:45   tsconfig.json 文件路径 => F:\ts-demo3-ui\tsconfig.json
[ts-paths] - 2019-5-17 17:07:45   开始编译文件
[ts-paths] - 2019-5-17 17:07:45   exec: tsc --project F:\ts-demo3-ui\tsconfig.json
(node:12232) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at TscCmd.build (F:\ts-demo3-ui\node_modules\ts-paths\lib\tscCmd.js:39:43)
(node:12232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.
PS F:\ts-demo3-ui>
---

**Comment by soraping** [comment]
tsconfig.josn文件夹里添加一个根目录属性：
```js
{
    "compilerOptions": {
        // ...
       "rootDir": "."
   }
}
```
然后在试下，还有，我确认下，你的电脑是不是windows，我用的是mac，编译过了，可能windows需要做个兼容，等下发个版本

**Comment by soraping** [comment]
我看了一下你的代码，因为ts解析器并不认得vue，也没有依赖关系，所以，编译后的代码里并不会有vue文件，所以，还是建议使用`webpack`，`ts-loader` 的作用就是让 `tsc` 把 `vue` 当作一个模块来处理

**Comment by lstoryc** [comment]
的确 我得是windows.  

酱紫 谢谢大佬

**Comment by lstoryc** [comment]
@soraping  大佬 大概啥时候发新版本？ 或者告诉我改哪里。。 项目急救中 哈哈 谢谢

**Comment by soraping** [comment]
```js
{
    "compilerOptions": {
        // ...
       "rootDir": "."
   }
}
```
在tsconfig.json里新增这个属性，windows是支持的，你能看到打包后的结果，但是没有.vue文件。
有两种解决方案：
- 写一个脚本，打包完成后将.vue和.html文件复制过去
- 写webpack

**Comment by lstoryc** [comment]
好 谢谢

**Comment by lstoryc** [comment]
@soraping  大佬 问多一个问题，你说可以使用webpack处理tsconfig里面定义得path替换问题，那这个插件是啥？ 我查了下ts-loader, 并没有发现处理 d.ts 里面得路径别名问题， 求指导

**Comment by soraping** [comment]
```JS
alias: {
  'vue$': 'vue/dist/vue.esm.js',
  '@': resolve('src')
}
```
webpack 配置里类似这样的
